Personal portfolio
Hasinarahman/Portfolio pull request #1
Opened 2024-07-31 18:59 UTC by Hasinarahman

Creating personal portfolio by using html,css and js.

2024-08-03 06:24 UTC, Hasinarahman commented
Hi dear @Najeeba-Qarqin,
finally I finished my project please ones review and give me feedback.

2024-08-03 19:54 UTC, Najeeba-Qarqin commented
Hi @Hasinarahman !
Well done you have done an amazing project👏

✔️ Created a professional Repo.
✔️ Correct use of Gitflow
✔️ Commit messages are meaningful 
✔️ Setup the linters correctly. 
✔️ No linter errors 
✔️ You have followed the Personal Portfolio project equirments
✔️ You have followed the all design of figma from UX/UI student
✔️ all of your links works good
✔️ Created the pull request correctly. 
✔️ Good and meaningful PR description 
✔️Your code is clean
✔️Your repo has a professional README.md
✔️Your code functionality is works fine. 
Just there is little missing in design of the project .

2024-08-03 19:57 UTC, Najeeba-Qarqin commented
In mobile version the heading of home page and the paragraph in about page should be separate. 
Your design: 
![IMG-20240804-WA0004](https://github.com/user-attachments/assets/cdcdb685-2450-4209-8f3a-ed380d7f2c8e)


Figma design: 
![IMG-20240804-WA0006](https://github.com/user-attachments/assets/f3d1f699-95fe-4ec4-9036-045d12f03c75)

2024-08-03 20:00 UTC, Najeeba-Qarqin commented
In the popup of your projects the languages section is not clear.
You should add them at the bottom of the module. 

![IMG-20240804-WA0002](https://github.com/user-attachments/assets/7677c5d6-ee9f-40e4-87e9-87088bd7b31a)

2024-08-03 20:03 UTC, Najeeba-Qarqin commented
And also the project cards are three in the row it should be two as the Figma design. 

Your design:

![IMG-20240804-WA0003](https://github.com/user-attachments/assets/9a829c47-782a-407f-9b62-26508410d3d6)


Figma design:


![IMG-20240804-WA0005](https://github.com/user-attachments/assets/3a6be8e6-c962-447f-8d26-27340b1cb925)

2024-08-04 07:44 UTC, Hasinarahman commented
Hi @Najeeba-Qarqin,
I emplement all of your sugestion so please review again.

2024-08-04 08:07 UTC, Najeeba-Qarqin commented
@Hasinarahman good job your project doesn't have any issues now and the status of your project is approved you can mention the mentor.

2024-08-04 08:39 UTC, Hasinarahman commented
Hi sir @Ahzamir
please check my project.

2024-08-05 12:44 UTC, Hasinarahman commented
@ahzamir
sir please check my project.

2024-08-10 21:09 UTC, ahzamir requested changes
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Well done Hasina, you have done a great job by implementing 98% of the project's requirements, just some minor changes needed inorder to get the final approval please check the comments below:

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Personal Portfolio and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive
❌Your design is same as the Figma Design

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-08-10 21:09 UTC, ahzamir commented on styles.css
- Well done @Hasinarahman  You implemented the design very well, and there is just 2 small changes needed on your project inorder to get the final approval:

### Humberger menu close button:
- The close button is not same as the Figma Design close button:
  - Your Design:
![image](https://github.com/user-attachments/assets/81cd496a-1cbb-49f4-9f27-e7b5bf357bad)
  - Figma Design:
  
![image](https://github.com/user-attachments/assets/057047f7-7186-4919-8561-d0f650e6e94f)


### Pop-up Modal:
- The pop-up modal for your Desktop version is too small, it should be bigger then this:
![image](https://github.com/user-attachments/assets/7b599290-8c28-4993-8a90-4a872b052e01)

2024-08-10 21:09 UTC, ahzamir commented on README.md
> +  (https://www.figma.com/design/IULNZAus8DhpOTmHgeEpDu/Portfolio?t=AvdQd1u18VKBqbar-0)
- Add it like this:
```
- [Figma Design](https://www.figma.com/design/IULNZAus8DhpOTmHgeEpDu/Portfolio?t=AvdQd1u18VKBqbar-0)
```

2024-08-10 21:09 UTC, ahzamir commented on README.md
> +
- Same in here add the links properly like this:
```
- [Link Text](The Link)
```

2024-08-12 03:36 UTC, Hasinarahman commented
Hello sir @ahzamir 
I emplement all of your sugestion so please review again.

2024-08-15 14:33 UTC, Hasinarahman commented
Hello sir @ahzamir 
please check my project.

2024-08-25 16:01 UTC, Hasinarahman commented
hi @ahzamir 
sir I did all the feedback you give me and this is the third week soo please check my project.

2024-08-26 18:04 UTC, ahzamir approved these changes
### Hi @Hasinarahman 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)


 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the JS Capstone project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive
✔️Your design is the same as the Figma designn

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-08-27 03:07 UTC, Hasinarahman commented
Thanks sir Ok I will share
@ahzamir

2024-08-27 03:07 UTC, merged